export const CATEGORIES = [
  "Text Generation", "Image Generation", "Marketing", "Coding", "Data Analytics",
  "Career", "Education", "Productivity", "Creative Writing", "Prompt Engineering",
] as const;

export type LibraryPrompt = {
  id: string; name: string; category: (typeof CATEGORIES)[number]; purpose: string;
  prompt: string; example: string; techniques: string[];
};

export const PROMPTS: LibraryPrompt[] = [
  { id: "blog-outline", name: "Structured Blog Outline", category: "Text Generation", purpose: "Plan a blog post before writing it.", prompt: "Act as a senior content strategist. Create an outline for a 1,000-word blog post on [topic] for [audience]. Include a hook, 4–5 H2 sections with 2 bullet points each, and a conclusion with a call to action. Return as Markdown.", example: "# Why Small Businesses Need AI\n## 1. The cost of manual work\n- ...", techniques: ["Role prompting", "Constraints", "Output formatting"] },
  { id: "summary-3", name: "Three-Level Summary", category: "Text Generation", purpose: "Summarise a document for different reading depths.", prompt: "Summarise the text below at three levels: (1) one sentence, (2) a 3-bullet executive summary, (3) a 150-word paragraph. Keep facts accurate and do not add new information.\n\nText: [paste]", example: "1. The report finds remote work increased output by 12%.\n2. • ...", techniques: ["Specific instructions", "Constraints", "Output formatting"] },
  { id: "product-photo", name: "Studio Product Shot", category: "Image Generation", purpose: "Clean e-commerce product imagery.", prompt: "Photorealistic studio product photo of [product] on a seamless off-white backdrop, soft diffused key light from the left, subtle reflection, 85mm lens, centered composition, high detail, minimal shadows.", example: "A crisp image of a ceramic mug with soft shadows on white.", techniques: ["Specific instructions", "Constraints"] },
  { id: "joburg-cyber", name: "Cyberpunk Cityscape", category: "Image Generation", purpose: "Cinematic concept art of a city.", prompt: "Cinematic wide shot of a futuristic Johannesburg skyline at sunset, Hillbrow tower glowing with neon signage, flying transit pods, wet streets reflecting magenta and teal light, volumetric haze, digital art, dramatic mood.", example: "A moody neon skyline with warm sunset sky.", techniques: ["Context", "Specific instructions"] },
  { id: "portrait-env", name: "Environmental Portrait", category: "Image Generation", purpose: "Human-centred scene with narrative.", prompt: "Environmental portrait of a young software developer working on a laptop in a sunlit co-working space, plants and whiteboards in the background, shallow depth of field, golden hour light through windows, eye-level camera, warm natural colours.", example: "A focused developer bathed in warm window light.", techniques: ["Context", "Specific instructions"] },
  { id: "ad-copy", name: "AIDA Ad Copy", category: "Marketing", purpose: "Persuasive short-form ads.", prompt: "Write 3 variations of Facebook ad copy for [product] using the AIDA framework (Attention, Interest, Desire, Action). Audience: [audience]. Max 60 words each. Include one emoji per variation.", example: "🚀 Tired of messy spreadsheets? ...", techniques: ["Constraints", "Examples", "Output formatting"] },
  { id: "brand-voice", name: "Brand Voice Rewriter", category: "Marketing", purpose: "Align copy to a brand tone.", prompt: "You are a brand copywriter. Rewrite the text below in a voice that is [warm, confident, jargon-free]. Keep the meaning and length within ±10%. Show the rewrite, then list 3 changes you made.\n\nText: [paste]", example: "Rewrite: ...\nChanges: 1. Replaced 'utilise' with 'use'...", techniques: ["Role prompting", "Constraints", "Output formatting"] },
  { id: "code-review", name: "Code Reviewer", category: "Coding", purpose: "Get structured feedback on code.", prompt: "Act as a senior [language] engineer. Review the code below for bugs, readability, and performance. Return a table with columns: Issue, Severity (Low/Med/High), Suggested fix. Then show the improved code.\n\n```\n[code]\n```", example: "| Issue | Severity | Fix |\n| Unused variable | Low | Remove ... |", techniques: ["Role prompting", "Output formatting"] },
  { id: "explain-code", name: "Explain Like I'm New", category: "Coding", purpose: "Understand unfamiliar code.", prompt: "Explain what this code does line by line for a first-year IT student. Use plain language, then give one real-world analogy.\n\n[code]", example: "Line 1 imports pandas, a library for tables...", techniques: ["Context", "Specific instructions"] },
  { id: "sql-gen", name: "SQL Query Builder", category: "Data Analytics", purpose: "Translate questions into SQL.", prompt: "Given tables orders(id, customer_id, total, created_at) and customers(id, name, region), write a SQL query to [question]. Explain each clause briefly and note any assumptions.", example: "SELECT c.region, SUM(o.total) ... GROUP BY c.region;", techniques: ["Context", "Specific instructions"] },
  { id: "insight", name: "Data Insight Narrator", category: "Data Analytics", purpose: "Turn numbers into a story.", prompt: "Here is a summary table: [paste]. Identify the 3 most important trends, one anomaly, and one recommended action. Write for a non-technical manager in under 150 words.", example: "Sales rose 18% in Q3, driven mostly by Gauteng...", techniques: ["Audience", "Constraints"] as string[] },
  { id: "cover-letter", name: "Tailored Cover Letter", category: "Career", purpose: "Match a cover letter to a job ad.", prompt: "Act as a career coach. Using my CV summary [paste] and this job ad [paste], write a 250-word cover letter that maps 3 of my skills to 3 requirements. Professional but warm tone. No clichés like 'I am writing to apply'.", example: "Dear Hiring Team, when I automated our weekly reports...", techniques: ["Role prompting", "Context", "Constraints"] },
  { id: "interview", name: "Mock Interview", category: "Career", purpose: "Practise interview answers.", prompt: "You are an interviewer for a junior data analyst role. Ask me one question at a time. After each answer, give feedback using the STAR method and a score out of 10. Start now.", example: "Question 1: Tell me about a time you cleaned messy data.", techniques: ["Role prompting", "Iterative refinement"] },
  { id: "study-plan", name: "Weekly Study Planner", category: "Education", purpose: "Structured learning schedule.", prompt: "Create a 4-week study plan to learn [topic] with 1 hour per weekday. Return a table: Week, Day, Topic, Resource type, Mini-exercise.", example: "| 1 | Mon | What is ML? | Video | List 3 ML apps |", techniques: ["Constraints", "Output formatting"] },
  { id: "quiz", name: "Concept Quiz Maker", category: "Education", purpose: "Test understanding.", prompt: "Generate 5 multiple-choice questions about [concept] at beginner level. Each with 4 options, the correct answer, and a one-line explanation.", example: "Q1. What does an LLM predict? A) Pixels B) Next token ✓ ...", techniques: ["Specific instructions", "Output formatting"] },
  { id: "meeting", name: "Meeting Notes to Actions", category: "Productivity", purpose: "Extract action items.", prompt: "From the meeting notes below, extract: decisions made, action items (owner + due date), and open questions. Use three Markdown headings.\n\nNotes: [paste]", example: "## Decisions\n- Launch moved to 12 Nov\n## Actions\n- Thabo: ...", techniques: ["Specific instructions", "Output formatting"] },
  { id: "email-triage", name: "Email Reply Drafter", category: "Productivity", purpose: "Fast, polite replies.", prompt: "Draft a reply to this email that [accepts/declines/asks for more info]. Keep it under 100 words, friendly-professional, and end with a clear next step.\n\nEmail: [paste]", example: "Hi Lerato, thanks for the invite — ...", techniques: ["Constraints", "Specific instructions"] },
  { id: "micro-story", name: "Micro-Fiction Generator", category: "Creative Writing", purpose: "Short stories with a twist.", prompt: "Write a 200-word story set in [place] about [character] with a surprising final line. Use sensory detail and present tense.", example: "The taxi rank hums at dawn...", techniques: ["Constraints", "Specific instructions"] },
  { id: "poem-style", name: "Style Imitation Poem", category: "Creative Writing", purpose: "Explore stylistic control.", prompt: "Write a 12-line poem about technology and family in the style of free verse, with one repeated refrain. Avoid rhyme.", example: "My grandmother holds the phone like a hymn book...", techniques: ["Examples", "Constraints"] },
  { id: "rctaf", name: "RCTACF Prompt Template", category: "Prompt Engineering", purpose: "A reusable prompt skeleton.", prompt: "Role: You are a [expert].\nContext: [background].\nTask: [what to do].\nAudience: [who it's for].\nConstraints: [length, tone, must/avoid].\nFormat: [bullets/table/JSON].", example: "Role: You are a nutritionist. Context: ...", techniques: ["Role prompting", "Context", "Constraints", "Output formatting"] },
  { id: "few-shot", name: "Few-Shot Classifier", category: "Prompt Engineering", purpose: "Teach by example.", prompt: "Classify customer feedback as Positive, Negative, or Neutral.\nExample: 'Delivery was fast!' → Positive\nExample: 'App crashes on login' → Negative\nNow classify: '[text]'", example: "→ Neutral", techniques: ["Examples", "Specific instructions"] },
];
