/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaseStudyRouteImport } from './routes/case-study'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as HowPromptsWorkRouteImport } from './routes/how-prompts-work'
import { Route as ImageRouteImport } from './routes/image'
import { Route as LabRouteImport } from './routes/lab'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ProjectRouteImport } from './routes/project'
import { Route as TextRouteImport } from './routes/text'
import { Route as CaseStudiesPromptEngineeringRouteImport } from './routes/case-studies.prompt-engineering'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudyRoute = CaseStudyRouteImport.update({
  id: '/case-study',
  path: '/case-study',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const HowPromptsWorkRoute = HowPromptsWorkRouteImport.update({
  id: '/how-prompts-work',
  path: '/how-prompts-work',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageRoute = ImageRouteImport.update({
  id: '/image',
  path: '/image',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectRoute = ProjectRouteImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => rootRouteImport,
} as any)
const TextRoute = TextRouteImport.update({
  id: '/text',
  path: '/text',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesPromptEngineeringRoute =
  CaseStudiesPromptEngineeringRouteImport.update({
    id: '/case-studies/prompt-engineering',
    path: '/case-studies/prompt-engineering',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/case-study': typeof CaseStudyRoute
  '/contact': typeof ContactRoute
  '/history': typeof HistoryRoute
  '/how-prompts-work': typeof HowPromptsWorkRoute
  '/image': typeof ImageRoute
  '/lab': typeof LabRoute
  '/library': typeof LibraryRoute
  '/project': typeof ProjectRoute
  '/text': typeof TextRoute
  '/case-studies/prompt-engineering': typeof CaseStudiesPromptEngineeringRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/case-study': typeof CaseStudyRoute
  '/contact': typeof ContactRoute
  '/history': typeof HistoryRoute
  '/how-prompts-work': typeof HowPromptsWorkRoute
  '/image': typeof ImageRoute
  '/lab': typeof LabRoute
  '/library': typeof LibraryRoute
  '/project': typeof ProjectRoute
  '/text': typeof TextRoute
  '/case-studies/prompt-engineering': typeof CaseStudiesPromptEngineeringRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/case-study': typeof CaseStudyRoute
  '/contact': typeof ContactRoute
  '/history': typeof HistoryRoute
  '/how-prompts-work': typeof HowPromptsWorkRoute
  '/image': typeof ImageRoute
  '/lab': typeof LabRoute
  '/library': typeof LibraryRoute
  '/project': typeof ProjectRoute
  '/text': typeof TextRoute
  '/case-studies/prompt-engineering': typeof CaseStudiesPromptEngineeringRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/case-study'
    | '/contact'
    | '/history'
    | '/how-prompts-work'
    | '/image'
    | '/lab'
    | '/library'
    | '/project'
    | '/text'
    | '/case-studies/prompt-engineering'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/case-study'
    | '/contact'
    | '/history'
    | '/how-prompts-work'
    | '/image'
    | '/lab'
    | '/library'
    | '/project'
    | '/text'
    | '/case-studies/prompt-engineering'
  id:
    | '__root__'
    | '/'
    | '/case-study'
    | '/contact'
    | '/history'
    | '/how-prompts-work'
    | '/image'
    | '/lab'
    | '/library'
    | '/project'
    | '/text'
    | '/case-studies/prompt-engineering'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaseStudyRoute: typeof CaseStudyRoute
  ContactRoute: typeof ContactRoute
  HistoryRoute: typeof HistoryRoute
  HowPromptsWorkRoute: typeof HowPromptsWorkRoute
  ImageRoute: typeof ImageRoute
  LabRoute: typeof LabRoute
  LibraryRoute: typeof LibraryRoute
  ProjectRoute: typeof ProjectRoute
  TextRoute: typeof TextRoute
  CaseStudiesPromptEngineeringRoute: typeof CaseStudiesPromptEngineeringRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-study': {
      id: '/case-study'
      path: '/case-study'
      fullPath: '/case-study'
      preLoaderRoute: typeof CaseStudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-prompts-work': {
      id: '/how-prompts-work'
      path: '/how-prompts-work'
      fullPath: '/how-prompts-work'
      preLoaderRoute: typeof HowPromptsWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image': {
      id: '/image'
      path: '/image'
      fullPath: '/image'
      preLoaderRoute: typeof ImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project': {
      id: '/project'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof ProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text': {
      id: '/text'
      path: '/text'
      fullPath: '/text'
      preLoaderRoute: typeof TextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/prompt-engineering': {
      id: '/case-studies/prompt-engineering'
      path: '/case-studies/prompt-engineering'
      fullPath: '/case-studies/prompt-engineering'
      preLoaderRoute: typeof CaseStudiesPromptEngineeringRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaseStudyRoute: CaseStudyRoute,
  ContactRoute: ContactRoute,
  HistoryRoute: HistoryRoute,
  HowPromptsWorkRoute: HowPromptsWorkRoute,
  ImageRoute: ImageRoute,
  LabRoute: LabRoute,
  LibraryRoute: LibraryRoute,
  ProjectRoute: ProjectRoute,
  TextRoute: TextRoute,
  CaseStudiesPromptEngineeringRoute: CaseStudiesPromptEngineeringRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
